### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by wallyqs** [dgkanatsios/AksNodePublicIPController#4]
Hi @dgkanatsios! Thanks again for sharing  this repo :) It seems that the approach stopped working on latest versions of Kubernetes like 1.18? Is there something that could be done to get the EXTERNAL_IP field with a public ip in k8s?

**Comment by dgkanatsios** [comment]
hey there! Support for Public IP per Node is on preview on AKS, would it help? https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-for-your-node-pools-preview

**Comment by kkyuri0419** [comment]
Hi @wallyqs, and @dgkanatsios , I assigned public ip to the node with the command in the link 
`az aks nodepool add -g MyResourceGroup2 --cluster-name MyManagedCluster -n nodepool2 --enable-node-public-ip`

Then, when I check the ip address with the command `az vmss list-instance-public-ips -g MC_MyResourceGroup2_MyManagedCluster_eastus -n YourVirtualMachineScaleSetName` ,
what I see is this.
` {
    "ddosSettings": null,
    "dnsSettings": null,
    "etag": "W/\"df3c2dcf-888d-4483-a5f2-467522890991\"",
    "extendedLocation": null,
    "id": "/subscriptions/d02010a5-e94a-48bf-9706-c1688136e15e/resourceGroups/MC_nats_nats_westus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-27069057-vmss/virtualMachines/1/networkInterfaces/aks-nodepool2-27069057-vmss/ipConfigurations/ipconfig1/publicIPAddresses/pub1",
    "idleTimeoutInMinutes": 30,
    "ipAddress": "13.XX.XXX.49",
    "ipConfiguration": {
      "etag": null,
      "id": "/subscriptions/d02010a5-e94a-48bf-9706-c1688136e15e/resourceGroups/MC_nats_nats_westus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-27069057-vmss/virtualMachines/1/networkInterfaces/aks-nodepool2-27069057-vmss/ipConfigurations/ipconfig1",
      "name": null,
      "privateIpAddress": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "MC_nats_nats_westus",
      "subnet": null
    },
    "ipTags": [],
    "location": null,
    "name": "pub1",
    "provisioningState": "Succeeded",
    "publicIpAddressVersion": "IPv4",
    "publicIpAllocationMethod": "Static",
    "publicIpPrefix": null,
    "resourceGroup": "MC_nats_nats_westus",
    "resourceGuid": "2d0caf59-366a-44cf-b805-91bd6b84d729",
    "sku": {
      "name": "Standard",
      "tier": null
    },
    "tags": null,
    "type": null,
    "zones": null
  },`

I want to connect leaf node running locally (nats server running locally on another laptop) to this nats in aks. 
The public ip address shown above which is  "ipAddress": "13.XX.XXX.49" is the one that I can use for leaf node connection?

And how do I open a port 7422 for that ip address? so that I can connect the leaf node to it.

**Comment by wallyqs** [comment]
OK I have found a workaround to be able to use public ips in a node.  This seems to be working right now and also populates the ExternalIP metadata:

```sh
az aks create \
    --resource-group nats \
    --name nats  \
    --node-count 3 \
    --node-vm-size Standard_DS2_v2 \
    --load-balancer-sku basic \
    --enable-node-public-ip 
```
